// <auto-generated />
namespace ServiceAuto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MobileNumberRefactor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MobileNumberRefactor));
        
        string IMigrationMetadata.Id
        {
            get { return "202101031407466_MobileNumberRefactor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
